[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/kurosawa_terraform.pem
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o ConnectionAttempts=10 -o ConnectTimeout=5

[db]
35.77.38.20

[ap]
13.192.206.92

[web]
35.75.7.200

[inner_dns]
52.68.253.34
